config/routes.rb
Rails.application.routes.draw do
	root 'articles#index'

	get 'auth/:provider/callback' => 'sessions#create'
	get 'auth/signout' => 'sessions#destroy'

	resources :categories, path: 'category', only: [:index, :create, :destroy]
	get 'category/:name' => 'articles#category'

	resources :articles do
		get 'archive', on: :collection # archive_articles_pathが生成
		get 'feed', on: :collection
		get 'admin', on: :collection
		get 'page/:page', action: :index, on: :collection
	end

end

app/models/article.rb
class Article < ActiveRecord::Base

	belongs_to :category, foreign_key: "category_id"

	belongs_to :author, foreign_key: "author_id", primary_key: "uid"

	has_many :article_attachments
	accepts_nested_attributes_for :article_attachments

	validates :title, presence: true, length: { maximum: 50 }
	validates :content, presence: true
	validates :category, presence: true
	validates :author_id, presence: true
	validate :author_id, :authenticate_user

	scope :recent, -> { order(:created_at).reverse_order }
	scope :previous, -> (id){where("id > ?", id).order(:created_at).first}
	scope :next, -> (id){recent.where("id < ?", id).recent.first}

	private
	def authenticate_user
		if !Author.exists?(uid:author_id)
			errors.add(:author_id, "は認証されたアカウントではありません")
		end
	end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
  validates :scname, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
	validates :name, presence: true, uniqueness: {case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  unless Rails.env.development?
    rescue_from Exception, with: :render_500
    rescue_from ActionController::RoutingError, with: :render_404
    rescue_from ActiveRecord::RecordNotFound,   with: :render_404
  end

  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end

  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy, :admin]


	def new
	   @post = Post.new
	end

	# GET /
	def index
		@articles = Article.recent.page params[:page]
	end

	# GET /articles/new
	def new
		@article = Article.new
		@title = "新規作成中"
	end

	# POST /articles
	def create
		@article = Article.new(article_params)
		# 今までにないカテゴリが付与されていた場合はカテゴリも新規作成
		if params[:new_category].present?
			@article.category_id = Category.find_or_create_by(name: params[:new_category]).id
		end
		@article.author_id = session[:user]["uid"]
		if @article.save
			redirect_to article_path(@article.id), notice: "投稿に成功しました"
		else
			flash.now[:alert] = @article.errors.full_messages
			render :new
		end
	end

	# GET /:id
	def show
		@article = Article.find(params[:id])
		@title = @article.title
	end

	# GET /:id/edit
	def edit
		@article = Article.find(params[:id])
		@title = "編集中:" + @article.title
	end

	# PATCH/PUT /articles/:id
	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			@article.update(category_id: Category.find_or_create_by(name: params[:new_category]).id) if(params[:new_category].present?)
			redirect_to article_path(@article.id), notice: "編集に成功しました"
		else
			flash.now[:alert] = @article.errors.full_messages
			render :edit
		end
	end

	# DELETE /articles/:id
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to :back, notice: '削除に成功しました'
	end

	# GET /category/:id
	def category
		if(category = Category.find_by(name: params[:name]))
			@title = "#{category.name}の記事一覧"
			@articles = category.articles.recent.page params[:page]
			render :index
		else
			redirect_to root_path
		end
	end

	# GET /article/feed
	def feed
		@articles = Article.recent.limit(20)
		respond_to do |format|
			format.xml { render :layout => false }
		end
	end

	# GET /archive/:year/:month
	def archive
		if params[:month].present?
			@articles = Article.by_month(params[:month], year: params[:year]).recent.page params[:page]
			@title = "#{params[:year]}年#{params[:month]}月の記事一覧"
		else
			@articles = Article.by_year(params[:year]).recent.page params[:page]
			@title = "#{params[:year]}年の記事一覧"
		end
		render :index
	end

	# GET /admin
	def admin
		@articles = Article.where(author_id: session[:user]["uid"]).recent.page params[:page]
		render :admin
	end

	private
		def article_params
			params.require(:article).permit(:title, :content, :category_id, :new_category)
		end

		# セッションを元にTwitterログイン済みかどうか
		def authenticate_user
			if session[:user].nil?
				redirect_to root_path, alert: '先にログインをしてください'
			elsif !Author.exists?(uid:session[:user]["uid"])
				redirect_to root_path, alert: 'このアカウントは承認されていません'+session[:user]["uid"]
			end
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	# POST /categories
	def create
		@category = Category.new(category_params)
		@category.save
	end

	# DELETE /categories/:id
	def destroy
		@category = Category.find(params[:id])
		@category.destroy
	end

	def index
		redirect_to root_path
	end

	private
		def category_params
			params.require(:category).permit(:name)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        data = request.env['omniauth.auth']
        if Author.exists?(uid:data.uid)
          session[:user] = data.info
          session[:user][:uid] = data.uid
          redirect_to root_path, notice: 'ログインしました'
        else
          redirect_to root_path, alert: 'このアカウントは権限がありません'
        end
    end

    def destroy
        session[:user] = nil
        redirect_to root_path, notice: 'ログアウトしました'
    end

    def oauth_failure
        redirect_to root_path, alert: 'ログインに失敗しました'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithCoderay < Redcarpet::Render::HTML
		def block_code(code, language)
			language ||= 'md'
			begin
				CodeRay.scan(code, language.to_sym).div
			rescue => e
				language = 'md'
				CodeRay.scan(code, language.to_sym).div
			end
		end
	end
	def markdown(text)
		redcarpet_options = {
			autolink: true, #http, https, ftp等の自動リンク
			space_after_headers: true, #「#」のあとに空白を必要とするか
			no_intra_emphasis: true, # foo_bar_bazをemタグにしない
			fenced_code_blocks: true, # 「```」によるコードブロック
			tables: true, # PHP-Markdownスタイルの表を有効化
			strikethrough: true, # ~~」によるdelタグの生成
		}
		html_render = HTMLwithCoderay.new(
			filter_html: true,
			hard_wrap: true,
			link_attributes: { rel: 'nofollow', target: "_blank" }
		)
		markdown = Redcarpet::Markdown.new(html_render, redcarpet_options)
		markdown.render(text)
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_article.html.slim
.panel.panel-default
	.panel-heading
		h1 = link_to(article.title, article_path(article))
		- if session[:user]
			= link_to " 編集", edit_article_path(article)
			= link_to " 削除", article, method: :delete, data: {confirm: '削除しますね?'}
	.panel-body
		.text-right
			p
				= article.created_at
				= link_to article.category.name, category_path(article.category.name)
		.article-body = markdown(article.content).html_safe

app/views/articles/_articles.html.slim
- articles.each do |article|
	.panel.panel-default
		.panel-body
			.row
				.col-md-9
					span = link_to(article.title, article_path(article))
				.col-md-3.text-right
					span.small = article.created_at.to_s :date
.text-center
	= paginate articles

app/views/articles/_editor.html.slim
- content_for(:additional_header) do
	= javascript_include_tag "editor.js"
= bootstrap_form_for(@article, inline_errors: false) do |f|
	
	.field
		= f.text_field :title, append: "000", autofocus: true
	
	.field
		= f.text_area :content, :size => "1x20"
	
	.field.form-inline
		= f.collection_select :category_id, Category.all, :id, :name, label: "カテゴリ"
		= text_field_tag :new_category, "", class: "form-control", placeholder: "新規追加する場合"
	.field
		= f.submit "投稿", class: "btn btn-primary btn-block", data: {disable_with: "送信中..."}

app/views/articles/_form.html.slim
= bootstrap_form_for(@article, inline_errors: false) do |f|
	- if @article.errors.any?
		- @article.errors.full_messages.each do |message|
			.alert.alert-danger = message
	.field
		= f.text_field :title
	.field
		= f.text_area :content
	.field
		= f.collection_select :category_id, Category.all, :id, :name
	.field
		= f.submit "投稿", class: "btn btn-primary"

app/views/articles/_sidebar.html.slim
- if session[:user]
	.well
		label = "@#{session[:user]["nickname"]}"
		ul
			li =link_to( "一筆", new_article_path)
			li =link_to("管理画面", admin_articles_path)
			li =link_to 'ログアウト', '/auth/signout'
- if Category.count != 0
.panel.panel-info#category
	.panel-heading カテゴリ
	ul.list-group
		- Category.all.each do |c|
			= link_to category_path(c.name), class: "list-group-item" do
				span = c.name
				span.badge = c.articles.count
- if Article.count != 0
	.panel.panel-info#archive
		.panel-heading アーカイブ
		ul.list-group
				- Time.now.year.downto(Article.first.created_at.year) do |y|
					= link_to archive_articles_path(year: y), class: "list-group-item" do
						span = y
						span.badge = Article.by_year(y).count

app/views/articles/admin.slim
.well
	label 記事の管理
	- if @articles
		table.table.table-striped
			thead
				tr
					th.col-md-9 タイトル
					th.col-md-3 機能
			tbody
				- @articles.each do |article|
					tr
						td = link_to(article.title, article_path(article))
						td
							.btn-group
								= link_to "編集", edit_article_path(article), class: "btn btn-primary"
								= link_to "削除", article, method: :delete, data: {confirm: '削除しますね?'}, class: "btn btn-danger"
	.text-center
		= paginate @articles

app/views/articles/edit.slim
= render "editor"

app/views/articles/index.slim
- if @articles
	= render partial: 'articles', locals: {articles: @articles}

app/views/articles/new.slim
= render "editor"

app/views/articles/show.slim
= render partial: 'article', locals: {article: @article}
ul.pager
  - if(next_article = @article.next)
    li
      = link_to "＜ #{next_article.title}", next_article
  - if(prev_article = @article.previous)
    li
      = link_to "#{prev_article.title} ＞", prev_article

app/views/layouts/application.html.slim
doctype html
html
	head
		title
			- if @title
				= @title+ " - " +Myblog::Application.config.title
			- else
				= Myblog::Application.config.title
		meta name="viewport" content="width=device-width, initial-scale=1.0"
		meta name="description" content="#{Myblog::Application.config.description}"
		= favicon_link_tag 'favicon.ico'
		= stylesheet_link_tag    "application", media: 'all'
		= javascript_include_tag "application"
		- if Rails.env.production?
			script src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
		= yield :additional_header
		= csrf_meta_tags
	body.no-thank-yu
		header
			.jumbotron
				.text-center
					h1 = link_to Myblog::Application.config.title, root_path
		.container
			- if flash[:notice]
				/ 単一のメッセージの場合
				- if flash[:notice].kind_of?(String)
					.alert.alert-success = flash[:notice]
				/ 複数のメッセージ(フォームのバリデーション等)の場合
				- else
					- flash[:notice].each do |message|
						.alert.alert-success = message
			- if flash[:alert]
				/ 単一のメッセージの場合
				- if flash[:alert].kind_of?(String)
					.alert.alert-danger = flash[:alert]
				/ 複数のメッセージ(フォームのバリデーション等)の場合
				- else
					- flash[:alert].each do |message|
						.alert.alert-danger = message
			.row
				.col-md-9
					- if Rails.env.production?
						.panel.panel-default
							ins.adsbygoogle(style="display:block" data-ad-client="#{Rails.application.secrets.adsense_id}" data-ad-slot="3059909240" data-ad-format="auto")
						javascript:
							(adsbygoogle = window.adsbygoogle || []).push({});
					= yield
				.col-md-3
					= render "sidebar"
			footer
				p.text-center = link_to Myblog::Application.config.title, root_path
	
	- if Rails.env.production?
		javascript:
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			ga('create', '#{Rails.application.secrets.google_analytics_id}', 'auto');
		  ga('send', 'pageview');